/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EpicsRouteImport } from './routes/epics'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EpicsIndexRouteImport } from './routes/epics.index'
import { Route as IssuesIdRouteImport } from './routes/issues.$id'
import { Route as EpicsIdRouteImport } from './routes/epics.$id'

const EpicsRoute = EpicsRouteImport.update({
  id: '/epics',
  path: '/epics',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EpicsIndexRoute = EpicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EpicsRoute,
} as any)
const IssuesIdRoute = IssuesIdRouteImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EpicsIdRoute = EpicsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EpicsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/epics': typeof EpicsRouteWithChildren
  '/epics/$id': typeof EpicsIdRoute
  '/issues/$id': typeof IssuesIdRoute
  '/epics/': typeof EpicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/epics/$id': typeof EpicsIdRoute
  '/issues/$id': typeof IssuesIdRoute
  '/epics': typeof EpicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/epics': typeof EpicsRouteWithChildren
  '/epics/$id': typeof EpicsIdRoute
  '/issues/$id': typeof IssuesIdRoute
  '/epics/': typeof EpicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boards'
    | '/epics'
    | '/epics/$id'
    | '/issues/$id'
    | '/epics/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boards' | '/epics/$id' | '/issues/$id' | '/epics'
  id:
    | '__root__'
    | '/'
    | '/boards'
    | '/epics'
    | '/epics/$id'
    | '/issues/$id'
    | '/epics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsRoute: typeof BoardsRoute
  EpicsRoute: typeof EpicsRouteWithChildren
  IssuesIdRoute: typeof IssuesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/epics': {
      id: '/epics'
      path: '/epics'
      fullPath: '/epics'
      preLoaderRoute: typeof EpicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epics/': {
      id: '/epics/'
      path: '/'
      fullPath: '/epics/'
      preLoaderRoute: typeof EpicsIndexRouteImport
      parentRoute: typeof EpicsRoute
    }
    '/issues/$id': {
      id: '/issues/$id'
      path: '/issues/$id'
      fullPath: '/issues/$id'
      preLoaderRoute: typeof IssuesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epics/$id': {
      id: '/epics/$id'
      path: '/$id'
      fullPath: '/epics/$id'
      preLoaderRoute: typeof EpicsIdRouteImport
      parentRoute: typeof EpicsRoute
    }
  }
}

interface EpicsRouteChildren {
  EpicsIdRoute: typeof EpicsIdRoute
  EpicsIndexRoute: typeof EpicsIndexRoute
}

const EpicsRouteChildren: EpicsRouteChildren = {
  EpicsIdRoute: EpicsIdRoute,
  EpicsIndexRoute: EpicsIndexRoute,
}

const EpicsRouteWithChildren = EpicsRoute._addFileChildren(EpicsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsRoute: BoardsRoute,
  EpicsRoute: EpicsRouteWithChildren,
  IssuesIdRoute: IssuesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
